{
 "title": "customer credit bank",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# Attrited Customer Profile" } },
  {
   "title": "Attrited Customer",
   "type": "stat",
   "gridPos": { "h": 32, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select avg(months_inactive_12_mon) as avg_inactive_12_month,\r\navg(months_on_book) as avg_month_on_book,\r\navg(contacts_count_12_mon) as avg_contacts_12_month,\r\navg(credit_limit) as avg_credit_limit,\r\navg(total_relationship_count) avg_product_used_count,\r\navg(avg_utilization_ratio) as avg_utilization_ratio\r\n-- avg(total_revolving_bal) as avg_rev_bal\r\nfrom customer_data_history_join\r\nwhere status = 'Attrited Customer';"
    }
   ]
  },
  {
   "title": "Credit limit Distribution",
   "type": "histogram",
   "description": "Most customers has credit limit below 4K",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 2 },
   "targets": [
    {
     "rawSql": "select credit_limit from customer_data_history_join;"
    }
   ]
  },
  {
   "title": "Income Category Distribution",
   "type": "piechart",
   "description": "Mostly, customer has less than $40K income Category",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select income_category, count(*) from customer_data_history_join group by 1;"
    }
   ]
  },
  {
   "title": "Months on Book Distribution ",
   "type": "histogram",
   "description": "the length of time an attrited customer has been with the company.",
   "gridPos": { "h": 7, "w": 13, "x": 4, "y": 10 },
   "targets": [
    {
     "rawSql": "select months_on_book\r\nfrom customer_data_history_join"
    }
   ]
  },
  {
   "title": "Average Month of Book and Total Product Usage of Attrited Customer in Each Age Range",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select  \r\n  age_range, \r\n  AVG(months_on_book) AS avg_month_on_book,\r\n  AVG(total_relationship_count) AS avg_product_usage \r\nFROM (\r\n  SELECT \r\n    CASE \r\n      WHEN customer_age BETWEEN 18 AND 25 THEN '18-25'\r\n      WHEN customer_age BETWEEN 26 AND 35 THEN '26-35'\r\n      WHEN customer_age BETWEEN 36 AND 45 THEN '36-45'\r\n      WHEN customer_age BETWEEN 46 AND 55 THEN '46-55'\r\n      WHEN customer_age BETWEEN 56 AND 65 THEN '56-65'\r\n      ELSE '65+'\r\n    END AS age_range, \r\n    months_on_book, \r\n    total_relationship_count, \r\n    idstatus\r\n  FROM customer_data_history_join\r\n) AS age_and_status_data \r\nWHERE idstatus = 2 -- only consider existing customers \r\nGROUP BY age_range \r\nORDER BY age_range;"
    }
   ]
  },
  {
   "title": "Average Month of Book in Each Income Category",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 4, "y": 17 },
   "targets": [
    {
     "rawSql": "WITH base_q AS (\r\n  SELECT \r\n    income_category, \r\n    status, \r\n    AVG(months_on_book) AS avg_month_on_book\r\n  FROM customer_data_history_join\r\n  GROUP BY 1,2\r\n)\r\nSELECT \r\n  income_category, \r\n  AVG(avg_month_on_book) FILTER (WHERE status = 'Attrited Customer') AS avg_mob_attrited,\r\n  AVG(avg_month_on_book) FILTER (WHERE status = 'Existing Customer') AS avg_mob_existing\r\nFROM base_q\r\nGROUP BY 1\r\nORDER BY 1 DESC;"
    }
   ]
  },
  {
   "title": "Average Month of Book by Gender",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 17 },
   "targets": [
    {
     "rawSql": "WITH base_q AS (\r\n  SELECT \r\n    gender, \r\n    status, \r\n    AVG(months_on_book) AS avg_month_on_book\r\n  FROM customer_data_history_join\r\n  GROUP BY 1,2\r\n)\r\nSELECT \r\n  gender, \r\n  AVG(avg_month_on_book) FILTER (WHERE status = 'Attrited Customer') AS avg_mob_attrited,\r\n  AVG(avg_month_on_book) FILTER (WHERE status = 'Existing Customer') AS avg_mob_existing\r\nFROM base_q\r\nGROUP BY 1\r\nORDER BY 1 DESC;"
    }
   ]
  },
  {
   "title": "Average Month of Book and Total Product Usage of Existing Customer in Each Age Range",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select  \r\n  age_range, \r\n  AVG(months_on_book) AS avg_month_on_book,\r\n  AVG(total_relationship_count) AS avg_product_usage \r\nFROM (\r\n  SELECT \r\n    CASE \r\n      WHEN customer_age BETWEEN 18 AND 25 THEN '18-25'\r\n      WHEN customer_age BETWEEN 26 AND 35 THEN '26-35'\r\n      WHEN customer_age BETWEEN 36 AND 45 THEN '36-45'\r\n      WHEN customer_age BETWEEN 46 AND 55 THEN '46-55'\r\n      WHEN customer_age BETWEEN 56 AND 65 THEN '56-65'\r\n      ELSE '65+'\r\n    END AS age_range, \r\n    months_on_book, \r\n    total_relationship_count, \r\n    idstatus\r\n  FROM customer_data_history_join\r\n) AS age_and_status_data \r\nWHERE idstatus = 1 -- only consider existing customers \r\nGROUP BY age_range \r\nORDER BY age_range;"
    }
   ]
  },
  {
   "title": "Average Month of Book in Each Age Range",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 11, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "WITH base_q AS (\r\n  SELECT \r\n    CASE \r\n      WHEN customer_age BETWEEN 18 AND 25 THEN '18-25'\r\n      WHEN customer_age BETWEEN 26 AND 35 THEN '26-35'\r\n      WHEN customer_age BETWEEN 36 AND 45 THEN '36-45'\r\n      WHEN customer_age BETWEEN 46 AND 55 THEN '46-55'\r\n      WHEN customer_age BETWEEN 56 AND 65 THEN '56-65'\r\n      ELSE '65+' \r\n    END AS age_range, \r\n    status, \r\n    AVG(months_on_book) AS avg_month_on_book\r\n  FROM customer_data_history_join\r\n  GROUP BY 1,2\r\n)\r\nSELECT \r\n  age_range, \r\n  AVG(avg_month_on_book) FILTER (WHERE status = 'Attrited Customer') AS avg_month_on_book_attrited,\r\n  AVG(avg_month_on_book) FILTER (WHERE status = 'Existing Customer') AS avg_month_on_book_existing\r\nFROM base_q\r\nGROUP BY 1\r\nORDER BY 2 DESC;"
    }
   ]
  },
  {
   "title": "Total Transaction Amount vs Credit Limit of Attrited Customer",
   "type": "xychart",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select credit_limit, total_trans_amt  \r\nfrom customer_data_history_join cdhj \r\nwhere idstatus = 2 \r\n-- group by 1"
    }
   ]
  },
  {
   "title": "Total Transaction Amount Distribution (Attrited Customer)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select \r\ntotal_trans_amt as average_amount_spent \r\nfrom customer_data_history_join cdhj where idstatus = 2;"
    }
   ]
  },
  {
   "title": "Total Transaction Amount Distribution (Existing Customer)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select \r\ntotal_trans_amt\r\nfrom customer_data_history_join cdhj where idstatus = 1"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 42 },
   "options": {
    "content": "# Attrited Customer Profile Demographic"
   }
  },
  {
   "title": "Customer Count ",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\r\ncount(*) filter (where status = 'Attrited Customer') as attrited,\r\ncount(*) filter (where status = 'Existing Customer') as existing\r\nfrom customer_data_history_join"
    }
   ]
  },
  {
   "title": "Attrited Customer by Gender",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with base_q as (\r\nselect customer_age::text as age, gender,\r\ncount(*) filter (where status = 'Attrited Customer') as attrited,\r\ncount(*) filter (where status = 'Existing Customer') as existing\r\nfrom customer_data_history_join\r\ngroup by 1,2\r\norder by 3 desc\r\n)\r\nselect sum(attrited) filter (where gender = 'M') as male_attrited,\r\nsum(attrited) filter (where gender = 'F') as femlate_attrited\r\nfrom base_q;"
    }
   ]
  },
  {
   "title": "Existing Customer based on gander",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with base_q as (\r\nselect customer_age::text as age, gender,\r\ncount(*) filter (where status = 'Attrited Customer') as attrited,\r\ncount(*) filter (where status = 'Existing Customer') as existing\r\nfrom customer_data_history_join\r\ngroup by 1,2\r\norder by 3 desc\r\n)\r\nselect sum(existing) filter (where gender = 'M') as male_attrited,\r\nsum(existing) filter (where gender = 'F') as femlate_attrited\r\nfrom base_q;"
    }
   ]
  },
  {
   "title": "Age Distribution of Attrited Customer by Gender",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select customer_age::text,\r\ncount(*) filter (where gender = 'M') as Male,\r\ncount(*) filter (where gender = 'F') as Female\r\nfrom customer_data_history_join\r\nwhere status = 'Attrited Customer'\r\ngroup by 1\r\norder by customer_age;"
    }
   ]
  },
  {
   "title": "The Age of the Most Attrited Female Customer",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with base_q as(\r\n  select customer_age, count(*) filter (where gender = 'F' and status = 'Attrited Customer') as count_age\r\n  from customer_data_history_join\r\n  group by 1\r\n)\r\n\r\nselect customer_age from base_q order by count_age desc limit 1;"
    }
   ]
  },
  {
   "title": "The Age of the Most Attrited Male Customer",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with base_q as(\r\n  select customer_age, count(*) filter (where gender = 'M' and status = 'Attrited Customer') as count_age\r\n  from customer_data_history_join\r\n  group by 1\r\n)\r\n\r\nselect customer_age from base_q order by count_age desc limit 1;"
    }
   ]
  },
  {
   "title": "Attrited Customer by Income Category in Each Gender",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select income_category,\r\ncount(*) filter (where gender = 'M') as Male,\r\ncount(*) filter (where gender = 'F') as Female\r\nfrom customer_data_history_join\r\nwhere status = 'Attrited Customer'\r\ngroup by 1\r\norder by 1;"
    }
   ]
  },
  {
   "title": "Attrited Customer by Card Category in Each Gender ",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select card_category,\r\ncount(*) filter (where gender = 'M') as Male,\r\ncount(*) filter (where gender = 'F') as Female\r\nfrom customer_data_history_join\r\nwhere status = 'Attrited Customer'\r\ngroup by 1\r\norder by 1 desc\r\n"
    }
   ]
  },
  {
   "title": "Count Each Age Categories",
   "type": "barchart",
   "gridPos": { "h": 17, "w": 8, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "\r\nSELECT \r\n    CASE \r\n      WHEN customer_age BETWEEN 18 AND 25 THEN '18-25'\r\n      WHEN customer_age BETWEEN 26 AND 35 THEN '26-35'\r\n      WHEN customer_age BETWEEN 36 AND 45 THEN '36-45'\r\n      WHEN customer_age BETWEEN 46 AND 55 THEN '46-55'\r\n      WHEN customer_age BETWEEN 56 AND 65 THEN '56-65'\r\n      ELSE '65+' \r\n    END AS age_range,\r\n    count(*) filter (where idstatus = 1) as Existing_Customer,\r\n    count(*) filter (where idstatus = 2) as Attrited_Customer\r\n from customer_data_history_join cdhj\r\n group by 1\r\n order by 1\r\n "
    }
   ]
  },
  {
   "title": "Income Category in Each Age Category (Attrited Customer)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "\r\nSELECT \r\n    CASE \r\n      WHEN customer_age BETWEEN 18 AND 25 THEN '18-25'\r\n      WHEN customer_age BETWEEN 26 AND 35 THEN '26-35'\r\n      WHEN customer_age BETWEEN 36 AND 45 THEN '36-45'\r\n      WHEN customer_age BETWEEN 46 AND 55 THEN '46-55'\r\n      WHEN customer_age BETWEEN 56 AND 65 THEN '56-65'\r\n      ELSE '65+' \r\n    END AS age_range,\r\n    count(*) filter (where income_category = 'Unknown') as unknown,\r\n    count(*) filter (where income_category = 'Less than $40K') as less_tran_40K,\r\n    count(*) filter (where income_category = '$40K - $60K') as between_40_and_60K,\r\n    count(*) filter (where income_category = '$60K - $80K') as between_60_and_80,\r\n    count(*) filter (where income_category = '$80K - $120K') as between_80_and_120K,\r\n    count(*) filter (where income_category = '$120K +') as more_than_120K\r\n from customer_data_history_join cdhj\r\n WHERE idstatus = 2\r\n group by 1\r\n "
    }
   ]
  },
  {
   "title": "Income Category in Each Age Category (Existing Customer)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "\r\nSELECT \r\n    CASE \r\n      WHEN customer_age BETWEEN 18 AND 25 THEN '18-25'\r\n      WHEN customer_age BETWEEN 26 AND 35 THEN '26-35'\r\n      WHEN customer_age BETWEEN 36 AND 45 THEN '36-45'\r\n      WHEN customer_age BETWEEN 46 AND 55 THEN '46-55'\r\n      WHEN customer_age BETWEEN 56 AND 65 THEN '56-65'\r\n      ELSE '65+' \r\n    END AS age_range,\r\n    count(*) filter (where income_category = 'Unknown') as unknown,\r\n    count(*) filter (where income_category = 'Less than $40K') as less_tran_40K,\r\n    count(*) filter (where income_category = '$40K - $60K') as between_40_and_60K,\r\n    count(*) filter (where income_category = '$60K - $80K') as between_60_and_80,\r\n    count(*) filter (where income_category = '$80K - $120K') as between_80_and_120K,\r\n    count(*) filter (where income_category = '$120K +') as more_than_120K\r\n from customer_data_history_join cdhj\r\n WHERE idstatus = 1\r\n group by 1\r\n "
    }
   ]
  }
 ]
}